apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jwm16yqp0-python
  janus-idp.io/tekton: jwm16yqp0-python
  backstage.io/kubernetes-id: jwm16yqp0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jwm16yqp0-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
